# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build:webapp
  - build:app


build:webapp:
  stage: build:webapp
  script:
    - cd webapp
    # Install Node Version Manager (NVM)
    - curl -o- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - ". ~/.nvm/nvm.sh"
    - nvm --version
    - nvm install 22.0.0
    - nvm use 22.0.0
    # install angular cli for building the webapp
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration production
  artifacts:
    when: on_success
    expire_in: 1 day
    paths: 
      - webapp/dist/
      
build:linux:
  stage: build:app
  script: 
    # install musl so that we can build a statically linked libc (for greater portability)
    - apt-get update -yqq
    - apt-get install -yqq musl-dev musl-tools
    - rustup target add x86_64-unknown-linux-musl
    - RUSTFLAGS="-C link-arg=-s" cargo build --target x86_64-unknown-linux-musl --package dsbox --release --features embedded_webapp
  needs:
    - job: build:webapp
      artifacts: true
  artifacts:
    when: on_success
    paths:
      - target/x86_64-unknown-linux-musl/release/dsbox
    expire_in: 1 week

build:windows:
  stage: build:app
  variables:
    CARGO_BUILD_TARGET: x86_64-pc-windows-gnu
  script:
    # install the cross compiler tools
    - apt-get update -yqq
    - apt-get install -yqq binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --target x86_64-pc-windows-gnu --package dsbox --release --features embedded_webapp
  needs:
    - job: build:webapp
      artifacts: true
  artifacts:
    when: on_success
    paths:
      - target/x86_64-pc-windows-gnu/release/dsbox
    expire_in: 1 week