on:
  push:
    tags:
      - "*"
jobs:
  build:webapp:
    runs-on: docker
    container:
      image: node:latest
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install packages
        working-directory: webapp
        run: |
          node -v
          npm install -g @angular/cli
          npm install
      - name: Build webapp
        working-directory: webapp
        run: |
          ng build --configuration production
      - name: Upload webapp artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: webapp/dist

  build:linux:
    runs-on: docker
    needs: build:webapp
    steps:
      - name: Download webapp artifact
        uses: actions/download-artifact@v3
        with:
          path: webapp_artifact
      - name: Ensure artifact downloaded
        run: ls -R webapp_artifact
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Checkout the tag
        uses: actions/checkout@v4
      - name: Install musl packages
        run: |
          apt-get update -yqq
          apt-get install -yqq musl-dev musl-tools
      - name: Install musl target
        run: |
          . $HOME/.cargo/env
          rustup target add x86_64-unknown-linux-musl
      - name: Build project
        run: |
          . $HOME/.cargo/env
          DSBOX_WEBAPP_DIR="webapp_artifact/webapp-angular/browser" RUSTFLAGS="-C link-arg=-s" cargo build --target x86_64-unknown-linux-musl --package dsbox --release --features embedded_webapp
      - name: Upload dsbox executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: dsbox-x86_64-linux-musl
          path: target/x86_64-unknown-linux-musl/release/dsbox