on:
  push:
    tags:
      - "*"
jobs:
  build-and-release:
    runs-on: docker
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v4
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install apt dependencies
        run : |
          apt-get update -y
          apt-get install clang lld llvm libgtk-3-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev librsvg2-dev -y
      - name: Install rust targets and tools
        run: |
          . $HOME/.cargo/env
          rustup target add x86_64-pc-windows-msvc
          cargo install cargo-xwin
          cargo install tauri-cli --git https://github.com/tauri-apps/tauri
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install webapp packages
        working-directory: webapp
        run: |
          npm install
      - name: Build webapp
        working-directory: webapp
        run: |
          npm run build-prod
      - name: Build DsBox Linux
        run: |
          . $HOME/.cargo/env
          cargo tauri build --bundles appimage
      - name: Build DsBox Windows
        run: |
          . $HOME/.cargo/env
          cargo tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc --no-bundle
      - name: Prepare release files
        run: |
          mkdir /tmp/release
          tar -zcf /tmp/release/x86_64-linux.tar.gz -C target/release/ dsbox
          cp target/release/bundle/appimage/DsBox_0.1.0_amd64.AppImage /tmp/release
          tar -zcf /tmp/release/x86_64-windows.tar.gz -C target/x86_64-pc-windows-msvc/release/ dsbox.exe
      - name: Upload release
        uses: actions/forgejo-release@v2.6.0
        with:
          direction: upload
          release-dir: /tmp/release