/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RpcRequest {
  jsonrpc: "2.0";
  method: string;
  id: string | number | null;
  params?:
    | unknown[]
    | {
        [k: string]: unknown;
      };
}
