/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RpcResponse = RpcResult | RpcError;

export interface RpcResult {
  jsonrpc?: "2.0";
  id: string | number | null;
  result: unknown;
}
export interface RpcError {
  jsonrpc?: "2.0";
  id: string | number | null;
  error: RpcErrorInfo;
}
export interface RpcErrorInfo {
  code: number;
  message: string;
  data?: unknown;
}
